[package]
name = "roma"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
libc = "0.2.139"
socket2 = "0.5.1"
memmap2 = "0.5.10"
env_logger = "0.10.0"
nix = "0.26.2"
bitflags = "1.3.2"
rand = "0.8.5"
